"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = void 0;
const express = require("express");
const share_1 = require("../controllers/share");
const user_1 = require("../controllers/user/user");
const tokens_1 = require("../services/tokens");
const userRouter = express.Router();
exports.userRouter = userRouter;
userRouter.get('/me', tokens_1.verifyAccessToken, user_1.getUser);
userRouter.get('/profiles/:userId', tokens_1.verifyAccessToken, user_1.getProfile);
userRouter.post('/:followingUserId/follow', tokens_1.verifyAccessToken, user_1.followUser);
userRouter.post('/profile-switch', tokens_1.verifyAccessToken, share_1.switchProfileToPublic);
userRouter.get('/me/following', tokens_1.verifyAccessToken, user_1.getFollowingUsers);
